google/cloudprober

.travis.yml

Don't run tools/build.sh any more, now that protobuf Go code is already checked in.

Don't run tools/build.sh any more.

---

.travis.yml

Update .travis.yml to build and push docker image only on Linux

Build and push docker image only on Linux

---

targets/gce/instances.go

Introduce a random delay before starting the instance list refresh loop. Also, introduce a brief delay between per-zone instance list API calls. If there are multiple cloudprober nodes running in a project, this will make sure that all nodes don't call the API at the same time.
PiperOrigin-RevId: 163301185

Introduce a random delay before starting the instance list refresh loop.

---

probes/dns/dns.go
probes/dns/dns_test.go
probes/http/http.go
probes/http/http_test.go
probes/ping/ping.go
probes/udp/udp.go

Rename sent/rcvd/rtt variables to total/success/latency.

---

probes/external/serverutils/serverutils.go

ORIGINAL_AUTHOR=Marçal Garolera Huguet <mgaro@google.com>
PiperOrigin-RevId: 171018896

Remove unnecessary logging in the external prober.

---

probes/external/external.go
probes/external/external_test.go
probes/external/serverutils/serverutils.go

Fix a bug in external probe (in server mode), where probe won't report any data if probe times out. Also, add tests for external probe's server mode.
PiperOrigin-RevId: 171330368

Fix a bug in external probe (in server mode).

---

probes/http/http.go

Update HTTP probe to support latency distributions.

---

targets/targets.go

= Rename t.l and t.r to t.lister and t.resolver.
= t.l can be very easily confused with logger as that's the field name we use for logger elsewhere.
= Also, in the same spirit, rename t.log to t.l.
PiperOrigin-RevId: 185426260

targets: Readability cleanup.

---

cloudprober.go
cmd/cloudprober.go
config/config.go
web/web.go

Start building web interface for cloudprober. It only provides a "/config" handler for now. We'll add more handlers over time.
PiperOrigin-RevId: 186660970

Web interface for cloudprober.

---

README.md
docs/content/_index.md
docs/content/concepts/probe.md
metrics/dist.go

Propose fix typos

---

probes/external/external_test.go
probes/udplistener/udplistener.go
servers/udp/udp.go
surfacers/stackdriver/stackdriver.go
web/web.go

fix misspell

---

probes/external/external.go

Reduce log verbosity increased in a recent change (commit 46dfe90).

---

config/config.go

Allow for environment variables expansion in configs.

---

config/config.go

Config documentation fixes.

---

cloudprober.go
targets/rds/client/cmd/client.go

Minor fixes that keep getting warned about while compiling.

---

probes/ping/ping.go

Resolving local host should not be a requirement for running the ping probe.
Looking at the code for icmp package, empty string for address should do the right thing:
https://github.com/golang/net/blob/adae6a3d119ae4890b46832a2e88a95adc62b8e7/icmp/listen_posix.go#L74
https://github.com/golang/net/blob/adae6a3d119ae4890b46832a2e88a95adc62b8e7/icmp/helper_posix.go#L22
PiperOrigin-RevId: 222485172

We should use zero "" network address if source is not specified.

---

examples/validators/cloudprober_validator.cfg

Add an example demonstrating the use of cloudprober validators.

Add validators example.

---

probes/dns/dns.go
probes/dns/dns_test.go

This can be used to check for specific patterns in the response section of the probe.
PiperOrigin-RevId: 224226004

Add regex validator to dns probe

---

probes/ping/ping.go
probes/ping/ping_test.go

We somehow missed it when we added the DISTRIBUTIONS support to other probes.
PiperOrigin-RevId: 224463669

Add distributions support to ping probe as well.

---

probes/external/external_test.go

= Fix flakiness in the TestProbeServerLocalPipeClose test. It closes the local end of the pipe while server may continue to read from the other end. This may result in an error sometimes and hence a test failure. To fix it, signal the intent that we are done through a doneChan and ignore pipe read failures if that's the case.
= Fix test probe server implementation to create the bufio.Reader only once before starting the loop. Creating a new bufio.Reader over io.Reader for every request may result in unpredictable behavior.
These changes bring down flakiness from ~12% to 0% (based on 200 measurements).
PiperOrigin-RevId: 228339056

Fix long standing flakiness in external probe tests.

---

probes/dns/dns.go

Add latency distribution support to DNS probe type.

---

tools/cloudprober_startup.sh

We can have another default file on the VM:
$ cat /etc/default/cloudprober_server
IMAGE=xx/yy/cloudprober_server
VERSION=latest
JOB_USER=cloudprober
CLOUDPROBER_PORT=9314
Also, remove the logic where we try to guess the image name. That's not very helpful.
PiperOrigin-RevId: 238361957

A few basic changes to allow running multiple cloudprober jobs on a VM.

---

probes/ping/ping.go
probes/ping/ping_test.go
probes/ping/pingutils_test.go

= Return an error during initialization is payload size is too big.
= Run probe for multiple packet sizes. Also refactor the testing code to make it easy to add further tests.
PiperOrigin-RevId: 239649757

Small improvements to ping probe.

---

prober/serviceimpl_test.go

Add tests for cloudprober service gRPC methods.

---

probes/external/external.go
probes/external/external_test.go

= Factor out common probe result processing code into a function - processProbeResult.
= Add validators support to external probe type.
PiperOrigin-RevId: 260943345

Reduce duplication and add validators support to external probe type.

---

metrics/map.go
rds/server/gcp/proto/config.proto
rds/server/kubernetes/proto/config.proto

Fix comments and a typo.

---

probes/external/external.go

Looks like I missed adding this when I added validators support for external probe.
PiperOrigin-RevId: 278466041

Add validation failure metrics to default metrics.

---

probes/external/external.go
probes/external/external_test.go
probes/external/payload_metrics_test.go
probes/ping/ping.go
probes/ping/ping_test.go

Add additional labels support to ping and external probes as well.

---

probes/udp/udp.go
probes/udp/udp_test.go

Add additional label support to UDP probe.

---

sysvars/runtime.go
sysvars/runtime_linux.go
sysvars/sysvars.go

Reduce verbosity of sysvars probe.

---

probes/http/http.go
probes/http/http_test.go
probes/http/proto/config.pb.go
probes/http/proto/config.proto
probes/http/request.go

Github issue: https://github.com/google/cloudprober/issues/319
PiperOrigin-RevId: 281802925

[HTTP Probe] Add support for running multiple HTTP requests in parallel.

---

rds/kubernetes/kubernetes.go
rds/kubernetes/services.go
rds/kubernetes/services_test.go
rds/kubernetes/testdata/services.json

Also fix a major bug where service lister was not plugged into the overall kubernetes provider.
PiperOrigin-RevId: 288593651

k8s RDS: Add support for public IPs for services.

---

.github/workflows/go.yml

* Build and push docker images only on master.
* Push versioned images only on tags.

Build docker images only on master.

---

rds/kubernetes/endpoints.go
rds/kubernetes/kubernetes.go
rds/kubernetes/pods.go
rds/kubernetes/pods_test.go
rds/kubernetes/services.go

Refactor Kubernetes module to make supported resource types and filters public.
Also while here, de-duplicate some of the stuff in ListResources implementation.
PiperOrigin-RevId: 290144185

RDS: Refactor kubernetes (k8s) provider.

---

rds/kubernetes/endpoints.go
rds/kubernetes/endpoints_test.go
rds/kubernetes/kubernetes.go

Fixes #370
PiperOrigin-RevId: 297769515

Add support for filtering k8s endpoints by port

---

.github/workflows/go.yml

Mv cloudprober file from the downloaded directory, not the directory itself.

Fix docker workflow.

---

rds/gcp/forwarding_rules.go

Fix log messages for newly added forwarding_rules support.

---

rds/gcp/gcp.go
rds/gcp/gcp_test.go

= Add support for resource path that doesn't contain any "/". For example, gcp://gce_instances should work.
= Add tests for this logic.
PiperOrigin-RevId: 306606829

rds/gcp: Improve the logic for selecting resource listers.

---

probes/grpc/grpc.go
probes/grpc/grpc_test.go
probes/proto/config.pb.go
probes/proto/config.proto

Add implementation for gRPC prober

---

probes/grpc/grpc.go
probes/grpc/grpc_test.go

Add targets refresh to grpc probes

---

probes/grpc/grpc_test.go

Specific change to fix test: look for an increment of at least one in "total" probes vs. previously we were looking for 5 successes.
PiperOrigin-RevId: 314956401

Fix a flaky grpc test

---

servers/http/http.go

Disable metrics logging in HTTP server.

---

rds/client/client.go

There is no need to take an exclusive lock while reading from it. This must have been an oversight.
PiperOrigin-RevId: 316557800

Change RDS client's mutex type from sync.Mutex to sync.RWMutex.

---

prober/prober.go
surfacers/file/file.go
surfacers/file/file_test.go
surfacers/postgres/postgres.go
surfacers/prometheus/prometheus.go
surfacers/prometheus/prometheus_test.go
surfacers/stackdriver/stackdriver.go
surfacers/surfacers.go
surfacers/surfacers_test.go

Wire up init context for surfacers.

---

probes/http/request.go
probes/http/request_test.go

This is to fix:
https://github.com/google/cloudprober/issues/438
PiperOrigin-RevId: 325289043

Set HTTP request's host header from target's "fqdn" label if available.

---

probes/external/external.go
probes/external/external_test.go

Fixes: https://github.com/google/cloudprober/issues/451
PiperOrigin-RevId: 329770045

Provide a way to access target port and labels in external probe's command.

---

prober/serviceimpl.go
prober/serviceimpl_test.go

Fix a pointer bug in ListProbes() method in serviceimpl.go and the corresponding test.
PiperOrigin-RevId: 330497498

Fix a bug in prober.ListProbes()

---

common/tlsconfig/tlsconfig.go
rds/client/client.go
rds/client/cmd/client.go

Also, in the RDS client command, provide an option to specify the cert's server name.
PiperOrigin-RevId: 331031879

Improve logging in RDS client.

---

probes/http/http.go

We cannot use req.Host for target name, as we now manipulate req.Host based on target labels.
PiperOrigin-RevId: 332178603

HTTP Probe: Use target name for logging.

---

cloudprober.go
cloudprober_test.go

Kubernetes automatically sets the <SERVICE>_PORT environment variable to service URL -  "tcp://<service-ip>:<service-port>". This conflicts with cloudprober's port environment variable CLOUDPROBER_PORT if someone runs cloudprober with service name cloudprober. To solve this, we used to parse CLOUDPROBER_PORT if it started with "tcp://". But this doesn't really work well, if someone wants to expose some other port from cloudprober, e.g. RDS. To avoid this confusion, we should just ignore CLOUDPROBER_PORT if it has been set by Kubernetes.
Context: https://github.com/google/cloudprober/issues/476
PiperOrigin-RevId: 333552093

Ignore CLOUDPROBER_PORT if set by Kubernetes.

---

rds/gcp/forwarding_rules.go
rds/gcp/gce_instances.go
rds/gcp/gce_instances_test.go

Couple of things in this CL:
= Keep per-zone/per-region cache. This will allow us to make progress even if API call for one zone or region fails.
= Shuffle zones/regions list in each refresh cycle, so that we go through them in different order every time. This may increase our chances to make progress in case of consistent API failures.
PiperOrigin-RevId: 334255401

Improve GCE resources refresh mechanism.

---

config/config.go
config/config_test.go

For gceCustomMetadata return "undefined" if metadata variable is not defined.

---

surfacers/pubsub/pubsub.go

Pubsub surfacer: Make pubsub attributes public.

---

targets/targets.go

This is to take care of the following race between targets refresh and lameduck creation:
Targets are refreshed few seconds after lameduck, and are deleted few more
seconds after that. If there is no min lameduck duration, we'll end up
ignoring lameduck in this case. With min lameduck duration, targets will
need to be refreshed some time (5m) after being lameducked.
PiperOrigin-RevId: 342204018

Introduce a time buffer between targets refresh and lameduck invalidation.

---

probes/http/request.go
probes/http/request_test.go

HTTP probe: Put square brackets around literal IPv6 hosts.

---

probes/grpc/grpc_test.go

This is to avoid race condition caused by one test's probe modifying the shared "resolver" state (in p.Init() while other is still accessing it.
Test failure caused by this race condition: https://github.com/google/cloudprober/runs/1415310591?check_suite_focus=true
PiperOrigin-RevId: 342993745

gRPC probe test: Wait for p.Start() to finish before finishing the test.

---

probes/http/http_test.go

= Try to get more than 4 EventMetrics from the data channel. If we ask for only 4, 3 of them can be from just one target. Now we ask for 10, and fail if we get less than 4.
= Instead of looking for at least two values per target on the channel, look for just one value, and use length of the slice to get the last value.
This is to avoid errors like this:
https://github.com/google/cloudprober/runs/1526782215#step:9:339
PiperOrigin-RevId: 346673534

Increase the robustness of end-to-end test.

---

probes/http/http.go

Don't launch a separate goroutine if there is only one request per probe.

---

probes/ping/pingutils.go

Darwin kernel never seems to compute checksum for IPv4.
Fixes: https://github.com/google/cloudprober/issues/537
PiperOrigin-RevId: 348598094

For OS X, compute checksum for IPv4 SOCK_DGRAM sockets as well.

---

probes/http/http.go
probes/http/http_test.go

= Do not run probe if request is nil.
= Recreate HTTP request at a regular interval if we are resolving targets ourselves.
This is to fix https://github.com/google/cloudprober/issues/543.
PiperOrigin-RevId: 350195940

Couple of fixes to HTTP request creation handling.

---

probes/udp/udp.go

In UDP probe, update additional labels on targets refresh.

---

rds/client/cmd/client.go

Automatically find cert server name even if project has domain name in its name.
PiperOrigin-RevId: 357878602

Update RDS client binary.

---

docs/content/how-to/validators.md
examples/validators/cloudprober_validator.cfg

Documentation for https://github.com/google/cloudprober/pull/561

Add HTTP header validation documentation

---

rds/client/cmd/client.go

Add an option to get public IP using RDS client binary.

---

validators/http/http_test.go

= Make them table-driven tests so that we can test more edge cases and it's easier to see what's going on.
= Also test the behavior when specifying both the conditions -- status code and header.
PiperOrigin-RevId: 359071786

Improve tests for HTTP validator.

---

probes/http/http.go

Don't wait first interval to start HTTP probing

---

servers/udp/udp.go
servers/udp/udp_nonwindows.go
servers/udp/udp_windows.go

= Don't re-create IPv6/IPv4 connections after each packet. Calling SetControlMessage on the newly created IPv6 connection is costly and unnecessary: http://screen/u7OdrWBPypN.
= Also, don't recreate the buffer for reading the packet.
PiperOrigin-RevId: 360270811

Optimize UDP server code.

---

probes/ping/icmpconn_unix.go

= Directly parse timestamp control message data, instead of using binary.Read. binary.Read is computationally expensive as it is very generic -- it requires creating a reader object, uses a bunch of reflection just to determine the variable size, etc.
CPU profile: http://screen/ktiXWyGRwZo
PiperOrigin-RevId: 362170922

Improve ping prober performance.

---

probes/http/http.go

Export resp-body only if configured to do so.

---

rds/kubernetes/endpoints.go
rds/kubernetes/endpoints_test.go

These labels can then be added to metrics, and be used for debugging.
Ref: https://github.com/google/cloudprober/issues/612
PiperOrigin-RevId: 382125535

Add "node" and "pod" labels to endpoints resources.

---

logger/logger.go

* Logging package didn't have this functionality when we implemented it ourselves in 2016.
* Now logging package does a better job of figuring out monitored resource[1]. It figures out where it's running beyond GCE (still Google properties though). For example, it checks if it's running on GKE, and if it is, it associates logs with GKE container instead of GCE instance[2].
Also, add instance_name to log labels. Logging API doesn't support setting instance_name for gce_instance resource type[3], but we can add it to the log labels. It will make debugging easier: http://screen/FzS1UWPWpYn
[1] - https://github.com/googleapis/google-cloud-go/blob/eb4444f7814c75729b0f26f8386961e7790b0cdd/logging/resource.go#L211
[2] - https://github.com/google/cloudprober/issues/580
[3] - …

Let logging package set the monitored resource.

---

sysvars/sysvars_gce.go

On some versions of GKE, and when some certain features are enabled, instance name is not available through metadata. Using environment variable HOSTNAME if instance name is not available.
Ref: https://github.com/google/cloudprober/issues/616
PiperOrigin-RevId: 383712025

Don't error out if we cannot fetch instance name on GCE.

---

probes/options/labels.go
probes/options/labels_test.go

This is to support use cases like the one described in:
https://github.com/google/cloudprober/issues/582
PiperOrigin-RevId: 385899284

Support specifying multiple substitutions in additional labels.

---

probes/udp/udp_test.go
probes/udplistener/udplistener_test.go

Wait for various goroutines to finish.
PiperOrigin-RevId: 387192294

Fix data race errors in UDP tests.

---

rds/file/file.go
rds/file/file_test.go

Ref: https://github.com/google/cloudprober/issues/634
PiperOrigin-RevId: 387390152

RDS file provider: Minor improvements to resource allocation.

---

probes/ping/icmpconn_nonunix.go
probes/ping/icmpconn_unix.go
sysvars/runtime.go
sysvars/runtime_linux.go
sysvars/runtime_nonlinux.go

Also, remove extra spaces from build constraints.
PiperOrigin-RevId: 387665491

Add missing copyright header.

---

rds/file/file.go
rds/file/file_test.go

If request contains if_modified_since field, use that field to decide whether to send all the resources in the response or not.
We always returns last_modified in the response. This timestamp corresponds to when lister's cache was refreshed from the actual file.
Ref: https://github.com/google/cloudprober/issues/641
& https://github.com/google/cloudprober/issues/634
PiperOrigin-RevId: 388502695

Add RDS-cache support to file provider.

---

surfacers/prometheus/prometheus.go
surfacers/prometheus/prometheus_test.go

Import PR: https://github.com/google/cloudprober/pull/581
PiperOrigin-RevId: 395856310

Prometheus surfacer: Delete metrics that have not been updated for 10 min
