- .travis.yml
Update .travis.yml to specify "trusty" dist for Linux as "docker" command seems to be borken on precise environment.
> Update .travis.yml to specify "trusty" dist for Linux

- cloudprober.go
- logger/logger.go
Ignore/truncate metric messages that are bigger than a certain threshold to protect against clogging all of cloudprober due to a bug in one of the modules.
ORIGINAL_AUTHOR=Clyde-Xu <clydexu@google.com>
PiperOrigin-RevId: 164014062
> Ignore/truncate metric messages that are too large.

- targets/lameduck/lameduck.go
- targets/rtc/rtc.go
- targets/rtc/rtc_test.go
- targets/rtc/rtcreporter/rtcreporter.go
- targets/rtc/rtcreporter/rtcreporter_test.go
- targets/rtc/rtcservice/rtcservice.go
- targets/rtc/rtcservice/rtcservice_stub.go
- targets/rtc/rtcservice/rtcservice_test.go
Relocate cloudprober/rtc package to targets/rtc/rtcservice. rtcservice is relevant only to targets so this improves code structure.
PiperOrigin-RevId: 164553980
> Relocate cloudprober/rtc package to targets/rtc/rtcservice.

- probes/dns/cmd/dns.go
- probes/dns/dns.go
- probes/dns/dns_test.go
- probes/external/cmd/external.go
- probes/external/external.go
- probes/external/external_test.go
- probes/http/cmd/http.go
- probes/http/http.go
- probes/http/http_test.go
- probes/options/options.go
- probes/ping/cmd/ping.go
- probes/ping/ping.go
- probes/ping/ping_test.go
- probes/probes.go
- probes/udp/cmd/udp.go
- probes/udp/udp.go
- probes/udp/udp_test.go
Make probe interface more flexible (and extensible) by encapsulating common probe options in a struct. We'll pass this struct at the time of probe initialization rather than passing all individual options separately. This will allow us to extend options without changing the API.
PiperOrigin-RevId: 175629673
> Make probe interface more flexible (and extensible).

- sysvars/runtime.go
- sysvars/runtime_linux.go
- sysvars/runtime_nonlinux.go
- sysvars/runtime_test.go
- sysvars/sysvars.go
Add a few Go runtime stats to help with debugging cloudprober performance/health.
cloudprober 1513308467341380164 1513308517 labels=ptype=sysvars,probe=sysvars uptime_msec=50001.34 gc_time_msec=1827920 mallocs=80363 frees=39703 cpu_usage=690762494
cloudprober 1513308467341380185 1513308567 labels=ptype=sysvars,probe=sysvars goroutines=161 mem_stats_sys_bytes=17836280
PiperOrigin-RevId: 179240256
> Add a few Go runtime stats.

- probes/probes.go
- targets/lameduck/lameduck.go
- targets/lameduck/lameduck_test.go
- targets/targets.go
- targets/targets_test.go
Refactor lameduck package to make it more intuitive and testing friendly.
= Define a new interface called Lister that implements only List() method. Use this interface for global singleton rather than the whole lameduck.Service. We need to share only Lister among lameduck users.
= Remove package level functions as they create more confusion than convenience. To avoid passing around global lister, provide a GetDefaultLister() method.
= Subsequently change targets.Targets struct to include a ldLister field that will be initialized to lameduck.GetDefaultLister() at the time of targets creation.
= Also remove the IsLameducking() method. It's not providing much value.
PiperOrigin-RevId: 181194094
> Refactor lameduck package

- metrics/eventmetrics.go
- metrics/eventmetrics_test.go
Optimize EventMetrics stringer for memory allocation. This function is called too many times and based on profiling is responsible for significant number of object allocations:
http://gpaste/6575839500042240
Benchmark results show significant improvement in time spent per op, 1.9 (1.4 if run for 20s) vs 4.8.
Before this change:
BenchmarkEventMetricsStringer-33    	  300000	      4830 ns/op
After this change:
BenchmarkEventMetricsStringer-16    	 1000000	      1928 ns/op
PiperOrigin-RevId: 186687177
> Metrics performance optimization.

- probes/udp/udp_test.go
Sub-100ms timeouts cause tests to fail on travis MacOS environment. I verified that tests pass with this change:
https://github.com/google/cloudprober/commit/ee9edbe2874d201ce8969b6d92a2f0d77a8d00ad
PiperOrigin-RevId: 186721577
> Fix UDP tests for travis MacOS environment.

- .travis.yml
- Makefile
= Make ca-certificates.crt an independent target so that nothing is done if ca-certificates.crt is already in the current dir.
= If DOCKER_VERSION is specified, use it for docker image tag, otherwise fallback to cloudprober version.
PiperOrigin-RevId: 191116206
> Makefile changes.

- metrics/float.go
On ARM system, the int type is defaulting to the size of int32 and can easily be overrun. As discussed in #117, we can skip trimming the trailing zeros. It's not adding much value and making the code obscure.
PiperOrigin-RevId: 193150323
> float: Don't cast a float value as an int

- cloudprober.go
- logger/logger.go
- metrics/eventmetrics.go
- metrics/map.go
- metrics/proto/dist.proto
- probes/dns/dns.go
- probes/external/external.go
- probes/external/proto/server.pb.go
- probes/external/proto/server.proto
- probes/http/http.go
- probes/ping/ping.go
- probes/probes.go
- probes/udp/proto/config.pb.go
- probes/udp/proto/config.proto
- probes/udp/udp.go
- servers/udp/udp.go
- surfacers/stackdriver/stackdriver.go
- surfacers/surfacers.go
- sysvars/runtime.go
- targets/gce/forwarding_rules.go
- targets/lameduck/lameduck_test.go
- targets/lameduck/proto/config.pb.go
- targets/lameduck/proto/config.proto
- targets/rtc/rtc_test.go
- targets/targets.go
- web/web.go
Also, to improve the readability, refactor the HTTP request handling part of the runProbe into a separate function: httpRequest.
(Note: This change also includes some unrelated TODO cleanups.)
PiperOrigin-RevId: 193549658
> Don't verify the payload pattern in case of a response read error.

- targets/rtc/rtcservice/rtcservice.go
List can fail for many reasons, which don't have anything to do with the configuration problems. We should either examine the List() error to find out the actual cause of failure or just not List() during init(). I am going with the latter. I have added a TODO to explore the former.
PiperOrigin-RevId: 202541985
> rtcservice: Don't try to list during initialization.

- docs/content/getting-started.md
Link is broken in documentation, because file was moved in `proto/` directory.
> Fix config.proto url in getting started doc

- probes/probes_status_tmpl.go
- servers/servers.go
- surfacers/surfacers.go
- web/status_tmpl.go
- web/web.go
= Consolidate the main status template code in a single file - status_tmpl.go. This file will define the HTML structure of the page.
= Move servers and surfacers status HTML handling to their respective packages.
PiperOrigin-RevId: 224552514
> Restructure the status template to improve readability.

- logger/logger.go
Generic logging doesn't need any extra state and thus we can handle the case of a nil receiver gracefully.
PiperOrigin-RevId: 224564914
> Use generic logging if the logger.Logger is nil.

- probes/probes.go
- probes/probes_status_tmpl.go
- sysvars/sysvars.go
- web/status_tmpl.go
- web/web.go
= Show cloudprober version. This version is added the build time through the linker -X flag (if built using make)
= Show start time. Add a function to sysvars to fetch the start time.
= Show a link to the config handler (/config).
= Use better formatting (proto.MarshalTextString) for probe conf.
PiperOrigin-RevId: 225104565
> Further improvements to the status page (/status).

- probes/probes_status_tmpl.go
- servers/servers.go
= We need to escape '%'.
= Servers don't have a name field. Remove it from the template.
PiperOrigin-RevId: 225115973
> Fix the status page:

- surfacers/file/file.go
Golang's bytes.Buffer.Bytes() has a rather non-obvious behavior. It doesn't make a copy of the bytes but simply returns a reference to the underlying location. If we write to the same buffer again before bytes have been compressed, we'll have a case of data corruption.
PiperOrigin-RevId: 228738717
> Copy compression buffer's bytes into a new location rather than just copying the reference.

- docs/content/concepts/probe.md
Missing `/proto` folder on probe `proto` config url.
> Fix wrong proto link on probe documentation

- .travis.yml
See https://github.com/google/cloudprober/issues/199.
> Add an environment variable to skip UDP probe tests for OSX

- servers/http/http.go
- servers/http/http_test.go
= Instead, update the request metric in the request handler itself.
= Also, while here, replace fmt.Fprintf by w.Write in request handler. fmt makes arguments (response string) escape to heap and requires reflection which isn't the fastest thing.
= Store static responses as bytes, rather than strings to avoid one conversion.
I see minor improvements to CPU usage after this change.
PiperOrigin-RevId: 230983788
> servers/http: Don't wake up statskeeper goroutine for every request.

- probes/external/external.go
- probes/external/external_test.go
Distributions support is missing in DNS probe as well, I'll add that in a follow up CL.
Fixes: https://github.com/google/cloudprober/issues/197
PiperOrigin-RevId: 231233226
> Add latency distributions support to external probe.

- surfacers/prometheus/prometheus_test.go
- validators/http/http_test.go
Go 1.12 (rightly) enforces the formatting args now.
PiperOrigin-RevId: 233967054
> Fix format string in a couple of places.

- surfacers/prometheus/prometheus.go
Using a shared "done" channel may result in panic if an ongoing HTTP handler reads the channel before the handler for which the request has actually finished. See https://github.com/google/cloudprober/issues/222 for more details.
PiperOrigin-RevId: 242071124
> Fix a bug in prometheus surfacer's HTTP query handler.

- surfacers/stackdriver/stackdriver.go
While checking if "batch" option has been set, first check if config itself has been provided.
PiperOrigin-RevId: 253042872
> Fix a recently introduced bug in stackdriver surfacer initialization.

- probes/ping/ping.go
- probes/ping/ping_test.go
Earlier we were skipping updating any target specific data structure if target fails to resolve. We should update the results map regardless of wether target resolves or not.
See https://github.com/google/cloudprober/issues/264 for more details.
PiperOrigin-RevId: 259473838
> Ping probe: Update results map even for the targets that don't resolve.

- config/runconfig/runconfig.go
- prober/prober.go
- targets/lameduck/lameduck.go
- targets/targets.go
- targets/targets_test.go
= As we standardize more towards RDS targets (and hence a common configuration format), the case of running a local RDS server will become more common. For example, for kubernetes targets, we are going to support only RDS format and that requires running an RDS server, either local or remote.
= Advantage of sharing the entire RDS server (through runconfig), instead of just the server address, is that client can directly use the server without going through the gRPC server.
PiperOrigin-RevId: 267216603
> Provide a mechanism to find the local RDS server and if rds_server_address is not given, use that.

- concepts/probe/index.html
This file was renamed in commit ec30bb3ad30547ed4db7b1627dd7b7ff1b5587b0.
> Fix incorrect link to server.proto

- docs/config.toml
- docs/content/concepts/probe.md
- docs/content/getting-started.md
- docs/content/how-to/extensions.md
- docs/content/how-to/external-probe.md
- docs/themes/hugo-material-docs/static/stylesheets/highlight/highlight.css
This also includes the fix in https://github.com/google/cloudprober/pull/281 which I incorrectly applied to the hugo output.
Using `pygmentsUseClasses = true` fixes very incorrect code highlighting shown when using `hugo server`, before:
after:
> Static Site Tweaks

- docs/config.toml
- docs/content/concepts/probe.md
- docs/content/getting-started.md
- docs/content/how-to/extensions.md
- docs/content/how-to/external-probe.md
- docs/themes/hugo-material-docs/static/stylesheets/highlight/highlight.css
This reverts commit 546497ef25e34de7006a12a9264bf605cf67121b.
Some code highlighting is getting broken with the above commit. I believe there is some problem with hugo and "pygmentsUseClasses". I remember running into something like this a long time ago. I'll revert for now and investigate later.
> Revert "Static Site Tweaks (#283)"

- targets/lameduck/lameduck.go
- targets/rds/server/gcp/pubsub.go
- targets/rds/server/gcp/rtc_variables.go
= Log the list of lameducked targets.
= Log an INFO log before starting the receiver for the pub/sub subscription.
= Don't log for each run of rtc_variables.expand().
PiperOrigin-RevId: 275397194
> A few logging fixes.

- targets/gce/gce.go
Endpoint objects include port (not applicable for GCE instances) and labels as well.
PiperOrigin-RevId: 278499487
> Add ListEndpoints() support to GCE targets.

- probes/dns/dns.go
- probes/external/external.go
- probes/http/http.go
- probes/options/options.go
- probes/ping/ping.go
- validators/integrity/integrity.go
- validators/integrity/integrity_test.go
- validators/regex/regex.go
- validators/regex/regex_test.go
- validators/validators.go
- validators/validators_test.go
= Instead of making validators.Validator an interface{} that various types of validators implement, make it a concrete struct with a function field Validate() that is implemented differently based on the validator type in the config. This has a few advantages:
++ Individual validator types don't have to keep up with the interface changes as we extend the validators over time. For example, RegexValidator's validator can take just one input that it cares about (responseBody), instead of taking everything and then ignoring.
++ Use of Validator (interface{}) and ValidatorWithName (struct) was a little confusing. Making Validator a struct does away with that need.
++ Validators are called very often (per probe per target) and interface->actual object resolution can be slightly expensive. On …
> Refactor validators to make extending them easier.

- logger/logger.go
- logger/logger_test.go
= Make it possible to enable debug log by log name (--debug_logname_regex=<logNameRegex>).
= Add a flag do disable cloud logging (--disable_cloud_logging).
= Provide a way to enable debug log and disable cloud through environment variables: CLOUDPROBER_DEBUG_LOG, CLOUDPROBER_DISABLE_CLOUD_LOGGING.
Example run:
./cloudprober --config_file=/tmp/cloudprober.cfg --debug_log_regex=.*gcs.* \
--debug_logname_regex=.*gcs.* --logtostderr
To disable cloud logging for all subsystems:
./cloudprober --config_file=/tmp/cloudprober.cfg --disable_cloud_logging
Fix #322.
PiperOrigin-RevId: 285027647
> Cloudprober logging improvements.

- probes/http/request.go
Fixes: https://github.com/google/cloudprober/issues/331
Background: https://github.com/golang/go/issues/7682
PiperOrigin-RevId: 285370151
> HTTP probe: For "Host" header set request's Host field.

- rds/kubernetes/client.go
> K8s RDS: Return an error if API response status code is not 200.

- metrics/payload/payload.go
When updating a metric value for a distribution always return after parsing the distribution value.
For formats that are sending all the values as a list current behavior will update the value but will log an error when trying to parse it as value. For distribution values with "dist" is a double counting bug (every parsed value is added twice).
PiperOrigin-RevId: 286751909
> When updating a metric value for a distribution always return after parsing the distribution value.

- cmd/cloudprober.go
- common/file/file.go
- common/file/file_test.go
- common/oauth/bearer.go
- common/oauth/oauth.go
- common/tlsconfig/tlsconfig.go
File module provides an interface "ReadFile" that either reads the file from the disk using ioutil, or, if its path starts with "gs://", retrieves it from the GCS over HTTP.
Use this new interface to read various files like OAuth token, JSON key, TLS cert, and even the config file.
PiperOrigin-RevId: 288072059
> Add a common "file" module with support for reading files from GCS.

- Makefile
Build an image with the latest version and then tag it with the tag based docker version.
> Fix docker build in Makefile

- go.mod
- go.sum
- prober/proto/service.pb.go
- rds/gcp/gce_instances.go
- rds/gcp/gce_instances_test.go
- rds/gcp/gcp.go
- rds/gcp/pubsub.go
- rds/gcp/pubsub_test.go
- rds/gcp/rtc_variables.go
- rds/gcp/rtc_variables_test.go
- rds/proto/rds.pb.go
- servers/grpc/proto/grpcservice.pb.go
rds/gcp: Make project optional in resource path and some other improvements.
= If project is not provided and only one project is configured in the provider, we use that project.
= Make GCP resource-type implementations have uniform interfaces.
PiperOrigin-RevId: 291809215
> rds/gcp: Make project optional in resource path and some other improvements.

- rds/client/client.go
- rds/client/srvlist.go
- rds/client/srvlist_test.go
= Add a resolver called "srvlist" that works with the comma-separated list of addresses. It sets the load balancing policy to round robin.
= Configure RDS client to use srvlist resolver if RDS server address starts with "srvlist".
Not making srvlist a common module right now. We can do that if we find more uses of it. May be the new "grpc" probe can use it.
PiperOrigin-RevId: 292201109
> Add load balancing support to RDS client.

- config/config.go
Also while here improve the documentation of the macros.
PiperOrigin-RevId: 292290547
> Add a mechanism to get GCE custom metadata in cloudprober config.

- surfacers/prometheus/prometheus.go
- surfacers/prometheus/prometheus_test.go
See https://github.com/google/cloudprober/issues/364 for the background.
= For distributions, don't record derived metrics: <metric>_sum, <metric>_count, <metric>_bucket as independent metrics. Instead of that, store derived metric names in the data keys.
PiperOrigin-RevId: 295877661
> Fix metrics "TYPE" for histogram (distributions) metrics.

- sysvars/sysvars_gce.go
This is what we use everywhere else:
https://github.com/google/cloudprober/blob/921faa63ccf2773a897b76718569aecf2cf4e3d4/probes/options/options.go#L225
https://github.com/google/cloudprober/blob/921faa63ccf2773a897b76718569aecf2cf4e3d4/rds/server/filter/utils.go#L61
PiperOrigin-RevId: 304865716
> Replace label_<key> with labels_<key> for label variables.

- examples/extensions/myprober/myprobe/myprobe.go
- rds/client/client.go
- rds/client/client_test.go
- rds/client/cmd/client.go
- targets/endpoint/endpoint.go
- targets/gce/forwarding_rules.go
- targets/gce/gce.go
- targets/gce/gce_test.go
- targets/lameduck/lameduck.go
- targets/rtc/rtc.go
- targets/rtc/rtc_test.go
- targets/targets.go
- targets/targets_test.go
Targets' transition to ListEndpoints is complete now. Drop support for the old List() interface.
PiperOrigin-RevId: 306267875
> Cleanup targets interfaces.

- probes/grpc/grpc_test.go
Current test uses credential mismatch to cause connect failures and this is causing problems on MacOS.
Fixes #398.
PiperOrigin-RevId: 308321322
> Force probe failures by connecting to discard port

- cmd/cloudprober.go
- config/config.go
- config/config_test.go
gceCustomMetadata doesn't work in test environment as it requires access to GCE metadata.
PiperOrigin-RevId: 308766389
> Fix configtest functionality for configs with gceCustomMetadata macro.

- common/iputils/iputils.go
- common/iputils/iputils_test.go
- probes/options/options.go
- probes/options/options_test.go
- probes/probeutils/probeutils.go
- probes/probeutils/probeutils_test.go
- rds/client/client.go
Move IP utilities from probes/probeutils to common/iputils.
I found myself using the same methods while working on the file_based targets implementation.
PiperOrigin-RevId: 317436181
> Refactor IP utilities to allow for better reuse of them.

- probes/http/http.go
If keep_alive is enabled, use net/http/httptrace to get notified when new connections are done. On ConnectDone, update a new counter "connect_event" and log when connection takes place.
With this we'll see new connections in logs like this:
"Established a new connection to: 172.217.9.164:80"
PiperOrigin-RevId: 318599259
> Keep track of connections done for keep_alive HTTP probes.

- rds/kubernetes/kubernetes.go
- rds/kubernetes/services.go
- rds/kubernetes/services_test.go
= Fill in RDS resource's port with service's port.
= Allow filtering services by ports.
= For multiple ports in a service, create multiple RDS resources, each with name <service>_<port>.
Addresses: #420.
> Add ports support to Kubernetes services resource.

- cmd/cloudprober.go
- probes/external/external.go
= Use probe start context to start the external probe processes. This will make sure that external probe processes are killed cleanly once start context is canceled.
= On SIGINT and SIGTERM, cancel the start context and wait for a grace shutdown time period (default=5s).
This is in response to https://github.com/google/cloudprober/issues/413. I had been planning for this anyway.  We should also wire init context properly and make sure we can cleanup properly.
PiperOrigin-RevId: 318986425
> Handle external probe process termination more gracefully.

- sysvars/sysvars.go
- sysvars/sysvars_ec2.go
- sysvars/sysvars_test.go
= Provide an option to disable cloud metadata checks.
= Set AWS API retries to 0. Metadata checks should not really require an automatic retry.
PiperOrigin-RevId: 319344649
> Improve cloudprober startup time when not running on Cloud.

- sysvars/sysvars.go
Publish the cloned copy of the static EventMetrics, so that updating the timestamp in the next cycle doesn't race with the reads by the surfacers.
PiperOrigin-RevId: 319547864
> Fix the concurrency bug introduced in the last change.

- rds/kubernetes/services.go
- rds/kubernetes/services_test.go
RDS client has already been changed to DNS-resolve resource's IP if it's not a valid IP address.
This is to support Kubernetes cases where ingress is given a hostname instead of an IP address, for example, AWS ELB. See https://github.com/google/cloudprober/issues/418 for more details.
PiperOrigin-RevId: 320145826
> kubernetes/services: Use ingress hostname if IP is empty but hostname is not.

- rds/gcp/pubsub.go
Within a loop "for k, v := range m", variables k and v are shared by all the loop iterations, as described in the Go specification (https://golang.org/ref/spec):
"The iteration variables may be declared by the "range" clause using a form of short variable declaration (:=). In this case their types are set to the types of the respective iteration values and their scope is the block of the "for" statement; they are re-used in each iteration. If the iteration variables are declared outside the "for" statement, after execution their values will be those of the last iteration."
In the related code, variable "sub" is shared by all the loop iterations. All the go routines within the loop may refer to a non-deterministic value (e.g. the last value updated by the loop), e.g., all sub.GetName() …
> Fix a possible race that uses goroutines on loop iterator variables.

- probes/options/labels.go
- probes/options/labels_test.go
- probes/options/options.go
- probes/options/options_test.go
- sysvars/sysvars_gce.go
= Enclose target based labels within '@@', for example: @target.label.zone@.
= Add support for adding a label based on target's name, using the keyword @target.name@.
While here also standardize on how we export label through sysvars -- use "label_<labelname>" instead of "labels_<labelname>.
PiperOrigin-RevId: 324673535
> Make target based additional labels easier to identify.

- rds/client/client.go
- rds/client/client_test.go
We anyway keep the target information in a map by name, i.e. we lose the information for duplicate targets anyway.
Also, log a warning if we get a duplicate target as it should ideally never happen.
Duplicate targets can lead to spurious behavior from probes:
https://github.com/google/cloudprober/issues/436
PiperOrigin-RevId: 325081938
> RDS: De-duplicate the targets list while refreshing state.

- rds/kubernetes/endpoints.go
- rds/kubernetes/endpoints_test.go
- rds/kubernetes/kubernetes.go
- rds/kubernetes/pods.go
- rds/kubernetes/pods_test.go
- rds/kubernetes/services.go
- rds/kubernetes/services_test.go
- rds/kubernetes/testdata/endpoints.json
- rds/kubernetes/testdata/pods.json
- rds/kubernetes/testdata/services.json
In Kubernetes, resource may have the same name across namespaces. Currently, this can lead to a pretty bizarre behavior. See https://github.com/google/cloudprober/issues/436#issuecomment-669007829 for background.
PiperOrigin-RevId: 325143549
> Kubernetes RDS: Use name and namespace as resource keys instead of just names.

- logger/logger.go
This is to fix https://github.com/google/cloudprober/issues/441.
PiperOrigin-RevId: 325283544
> Logger: Don't debug-log if logger is nil.

- metrics/eventmetrics.go
- metrics/eventmetrics_test.go
- metrics/map.go
- metrics/map_test.go
= Export allocs per run for New() and String() functions of EventMetrics and Map.
= Grow strings.Builder before writing to it, to reduce the number of allocations.
Allocs per run in string call:
Before: 12 (http://screen/KLKKM79AfSq)
After:   6 (http://screen/fVXeJHGudez)
We call String() a lot to export metrics. This change should help.
PiperOrigin-RevId: 325915027
> Metrics memory allocation visibility and performance improvements.

- probes/http/http.go
- probes/http/http_test.go
- probes/http/request.go
Currently request body reader returns io.EOF on the first "Read" itself. Default HTTP transport seems to use a byte slice of size 32768, which results in request body being truncated to 32768 bytes.
This change fixes that problem by using a buffered reader if request body is larger than a certain threshold (set to bytes.MinRead, same as used by ioutil.ReadAll).
PiperOrigin-RevId: 325915715
> Allow for request bodies larger than 32768 bytes.

- docs/content/how-to/run-on-kubernetes.md
Since Deployment in apps/v1beta1 is no longer served in Kubernetes 1.16 and apps/v1 is available since v1.9, I updated the doc for Kubernetes to use Deployment in apps/v1.
FYI: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
> Update Deployment to apps/v1 in gh-pages

- probes/http/request.go
- probes/http/request_test.go
= Use "fqdn" label for URL host as well. We already use it for host header.
= Use "url" label as relative URL if available.
PiperOrigin-RevId: 331224477
> HTTP probe: couple of changes in configuration through target labels

- probes/external/external.go
- probes/external/external_test.go
Fixes: https://github.com/google/cloudprober/issues/473
PiperOrigin-RevId: 332297177
> Use shell lex parser to parse external probe commands.

- probes/http/http.go
Some Google services, for example GCP IAP, don't set access token but set id_token in the OAuth token JSON. Use id_token if that's the case.
PiperOrigin-RevId: 335465851
> Check for ID token in OAuth token if access token is not set.

- cloudprober.go
The default gRPC server will be created if the grpc_port field is specified in the prober.cfg file, and the channelz service use use the same port as the default gRPC server.
PiperOrigin-RevId: 335665796
> Regitser channelz service to cloudprober default gRPC server. 

- surfacers/file/file.go
This will allow a bigger burst of EventMetrics and 10000 should not increase the memory usage by much.
PiperOrigin-RevId: 335890605
> Increase file surfacer buffer size to 10000 (from 1000).

- metrics/payload/payload.go
- metrics/payload/payload_test.go
- metrics/testutils/testutils.go
- metrics/testutils/testutils_test.go
- probes/external/external.go
- probes/external/external_test.go
- probes/grpc/grpc_test.go
If we are not aggregating metrics in cloudprober, we can export one EventMetrics per payload metric line, and with that we can support dynamic labels in the metric lines, for example, something like the following will work:
db_stats{name=db01,region=us-west-2,status=running,ptype=external,probe=external_test} 1.0
db_stats{name=db02,region=us-east-1,status=running,ptype=external,probe=external_test} 1.0
Implements: https://github.com/google/cloudprober/issues/466
PiperOrigin-RevId: 336164768
> External Probe: Allow dynamic labels for metrics that are not aggregated in cloudprober.

- metrics/payload/payload.go
- metrics/payload/payload_test.go
For example, we'll be able to parse the following string:
version{service="service A",dc="xx"} "version 1.5.0"
= Instead of splitting by spaces, parse the string from the beginning. Use opening and closing braces("{", "}") to find labels in the string.
= Metric names cannot have spaces. Consider everything before the first space to be a metric name.
PiperOrigin-RevId: 336970245
> Enhance payload parsing to support spaces in labels and string values.

- rds/gcp/forwarding_rules.go
- rds/gcp/gce_instances.go
- rds/gcp/gce_instances_test.go
- rds/gcp/testdata/instances.json
- rds/gcp/testdata/zones.json
Implement GCE instances discovery using the API directly (instead of API library).
= This will allow us to support early features that are not part of the API library yet.
= This is also more consistent with what we do for Kubernetes.
PiperOrigin-RevId: 341737797
> Implement GCE instances discovery using the API directly.

- probes/udp/udp.go
> Print Duration type as string, not decimal.

- docs/content/surfacers/stackdriver.md
Using `allowed_metrics_regex` from example gives:
```
invalid quoted string ".*\/http\/.*": unknown escape \/
```
> Escape slashes in Stackdriver documentation

- probes/http/http_test.go
= Read 100 instead of 10 EventMetrics. We are still running into cases where one target is able to produce 10 EventMetrics before any EventMetrics from another target show up. This caused one failure.
= Don't read stuff from slice if its length is 0 (less than 1).
I tested this change a few times (3 so far) to make sure this works:
https://github.com/google/cloudprober/pull/524
PiperOrigin-RevId: 346693076
> Increase the robustness of end-to-end test - part II.

- probes/udplistener/udplistener.go
- probes/udplistener/udplistener_test.go
In logErrs() we create a copy of p.errs. That ends up creating a new probeErrors struct instead of just creating a new reference (copy of the pointer). When we replace invalidMsgErrs and missingTargets in the copy of p.errs, we change only the new struct:
pe := p.errs
..
pe.invalidMsgErrs = make(map[string]string)
..
pe.missingTargets = make(map[string]int
Storing a pointer will make sure that we are modifying the probe's errs object.
PiperOrigin-RevId: 347708735
> Probe's errs field should be a pointer.

- probes/ping/cmd/ping.go
= Add a LogMetrics function to options that doesn't do anything.
= Add a command line flag to specify IP version.
Fixes: https://github.com/google/cloudprober/issues/532
PiperOrigin-RevId: 348549443
> Fix ping probe command.

- probes/ping/icmpconn_nonunix.go
- probes/ping/icmpconn_unix.go
- probes/ping/ping.go
- probes/ping/ping_test.go
Use SO_TIMESTAMP socket option (supported only on Unix systems) to capture kernel timestamp for incoming packets. This will make ping probe's latency measurement much more accurate.
Impact of this on intra-region latency measurement:
http://screen/wuOqxDmE4tT
Reference:
https://github.com/google/cloudprober/issues/531
https://github.com/google/cloudprober/issues/540
I tested this change on MacOS and Linux. Logic is not changing for Windows.
PiperOrigin-RevId: 350035725
> Ping: Capture and use kernel timestamp for latency computation.

- probes/grpc/grpc.go
- probes/grpc/grpc_test.go
- probes/http/http_test.go
- targets/statictargets.go
- targets/statictargets_test.go
- targets/targets.go
- targets/targets_test.go
Sometimes users put ports and URLs in static hostnames. Currently, either we silently drop such hosts, for example when doing HTTP probing, or use hostport as it is, for example in gRPC probe. Make this behavior consistent:
- Parse ports in host spec (e.g. test.com:8080) and create an endpoint.Endpoint from host-port combination. This will work across all probes.
- Check for forward-slashes in target host names, and fail if there are any.
More context: https://github.com/google/cloudprober/issues/543#issuecomment-754943940
PiperOrigin-RevId: 350508273
> Static targets handling improvements.

- cmd/cloudprober.go
- sysvars/sysvars_gce.go
> Cloudprober sysvars: adding machine_type to exported variables.

- surfacers/stackdriver/stackdriver.go
Getting "instance/name" metadata may fail while running on GKE.
Context:
https://github.com/google/cloudprober/issues/554
PiperOrigin-RevId: 352680291
> Stackdriver surfacer: don't fail if unable to get instance name.

- docs/content/surfacers/overview.md
I found surfacer typo like below
s/promethues/prometheus/
Thank you.
> Fix:  surfacer example typo

- probes/http/http.go
Log:
```
panic: runtime error: integer divide by zero
goroutine 77 [running]:
github.com/google/cloudprober/probes/http.(*Probe).gapBetweenTargets(...)
```
Found by playing with `file_targets`.
Minimum configuration to reproduce:
```
probe {
name: "1"
type: HTTP
targets {
file_targets {
file_path: "/dev/null"
re_eval_sec: 1
}
}
http_probe {
interval_between_targets_msec: 0
}
}
```
PiperOrigin-RevId: 359324571
> Fix "divide by zero" in HTTP probe

- logger/logger.go
This is what logs will look like:
I0310 20:45:58.163937   17958 server.go:66] [cloudprober.rds-server] rds.server: adding GCP provider with id: gcp
I0310 20:45:58.824389   17958 prober.go:293] [cloudprober.global] Starting probe: vm-to-vm
I0310 20:46:08.167776   17958 prometheus.go:250] [cloudprober.prometheus] Checking validity of new label: ptype
PiperOrigin-RevId: 362207163
> Add log name to generic log line.

- probes/external/external.go
- probes/external/external_test.go
Fix a bug where our process wait goroutine will not exit until the probe start context is explicitly canceled. This bug was introduced when we added handling for clean exit (June 2020: CR 318986425).
Add a test that would have caught this bug.
PiperOrigin-RevId: 366547916
> Fix a goroutine leaking bug in external probe.

- docs/content/surfacers/cloudwatch.md
This PR adds the documentation for the cloudwatch surfacer.
Reference to: https://github.com/google/cloudprober/pull/583 and https://github.com/google/cloudprober/pull/587
> docs: add documentation for cw surfacer

- docs/content/surfacers/cloudwatch.md
- docs/content/surfacers/overview.md
Staging this PR to align filtering docs as a follow on for #597. I'd spotted the cloudwatch docs needed a quick update so I took the opportunity to also write a bit of documentation for filtering metrics.
I'd also spotted I'd missed the surfacers overview -> cloudwatch reference so added that here.
There is a minor code change in the protobuf config and tests for cloudwatch so I think this PR needs splitting again? Let me know what's best.
> Docs: Filtering Metrics in Surfacers

- surfacers/cloudwatch/cloudwatch.go
- surfacers/cloudwatch/cloudwatch_test.go
- surfacers/common/options/options.go
- surfacers/common/transform/transform.go
- surfacers/common/transform/transform_test.go
- surfacers/stackdriver/stackdriver.go
- surfacers/stackdriver/stackdriver_test.go
- surfacers/surfacers.go
- surfacers/surfacers_test.go
Now that we have a central way to add failure metric, remove individual implementations.
PiperOrigin-RevId: 377314575
> Remove individual add-failure-metric implementations.

- probes/http/http.go
```
// Do more frequent listing of targets until we get a non-zero list of
// targets.
```
1 second should be more frequent than probe interval.
Addresses: https://github.com/google/cloudprober/issues/613
PiperOrigin-RevId: 382204217
> Wait for targets in smaller steps before entering HTTP probe loop

- surfacers/stackdriver/resource.go
- surfacers/stackdriver/stackdriver.go
- surfacers/stackdriver/stackdriver_test.go
NOTE: This change will break existing stackdriver queries for users who are running cloudprober on kubernetes and are querying metrics specifically from gce_instance. I'll include this detail in the release notes.
To fix: https://github.com/google/cloudprober/issues/580
PiperOrigin-RevId: 383801217
> Associate stackdriver metrics with correct resources on GKE.

- logger/logger.go
We currently check for l.logc being nil, but l.logger is better check, as it's possible that log client (l.logc) is not nil, but l.logger has not been initialized yet.
Ref: https://github.com/google/cloudprober/issues/616#issuecomment-879593718
PiperOrigin-RevId: 384639303
> Check for l.logger being nil before attempting to log remotely.

- common/metadata/metadata.go
- surfacers/stackdriver/resource.go
- sysvars/sysvars_gce.go
= Use KUBERNETES_SERVICE_HOST variable to decide if we are running on Kubernetes. This variable should always be set while running on Kubernetes.
= On GKE, metadata requests are handled by GKE metadata server which supports only a subset of the GCE metadata variables:
https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#gke_mds
While on GCE and Kubernetes, don't try to initialize other variables.
= For stackdriver metrics, use cluster-location instance attribute for resource "location", instead of instance zone. Fetching instance zone metadata may not work on GKE.
Ref: https://github.com/google/cloudprober/issues/616#issuecomment-879593718
PiperOrigin-RevId: 384765519
> Fix metadata retrieval when running on GKE.

- probes/dns/dns.go
- probes/external/external.go
- probes/http/http.go
- probes/options/labels.go
- probes/options/labels_test.go
- probes/ping/ping.go
- probes/udp/udp.go
- probes/udplistener/udplistener.go
Ref: https://github.com/google/cloudprober/issues/582
PiperOrigin-RevId: 386808079
> Make target's port available for labeling.

- rds/file/file_test.go
Instead of checking for lister time being after the file mod time, check for it not being before the file mod time.
File lister update time can be same as temp file's mod time. In some test environments, time.Now() may not change from one call to another.
Failure ref: https://github.com/google/cloudprober/runs/3196053886
PiperOrigin-RevId: 387668329
> Fix file provider test flakiness.

- probes/http/http.go
Without this option, keep-alive and parallel probing (multiple requests per probe) don't work very well together.
Note: Default MaxIdleConnsPerHost is 2.
PiperOrigin-RevId: 388287864
> Increase MaxIdleConnsPerHost based on requests-per-probe parameter.

- probes/ping/ping.go
> Update cloudprober ping MTU to 9001 to allow jumbo packets.

- probes/udplistener/udplistener.go
Godoc requires a newline and will treat indented text as codeblocks.
PiperOrigin-RevId: 393364160
> Fix docstring format to make godoc more readable.

- probes/external/serverutils/serverutils.go
This PR just fixes a regression in a comment. The comment is just some code that outlines how to use serverutils to parse incoming messages in an EXTERNAL-Probe in order to implement SERVER-mode there. 
The current comment lists imports that are not longer valid and I simply replaced the import statements with the correct ones.
No change on any running code performed through this PR. It should be safe to merge.
But as always please review carefully and use on your own risk.
> fixing the imports in the example

- probes/grpc/grpc.go
> Migrate gRPC insecure API call sites to use local credentials
